# See https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: node:12.11
    steps:
      - checkout
      - run:
          name: Flow
          command: |
            yarn install
            yarn run flow
